/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lab2.dataModel.User;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Quang
 */
public class UserForm extends javax.swing.JFrame {

    private List<User> list = new ArrayList<>();
    private DefaultTableModel tblModel;
    private static String url = "jdbc:sqlserver://localhost:1433;databaseName=Java2_Staff;user=sa;password=123;encrypt=false;";

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url);
    }

    /**
     * Creates new form UserForm
     */
    public UserForm() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        initData();
        fillTable();
    }

    public void fillTable() {
        while (tblModel.getRowCount() > 0) {
            tblModel.removeRow(0);
        }

        for (User user : list) {
            tblModel.addRow(new String[]{user.getUsername(), user.getPassword(), user.getRole()});
        }

        tblModel.fireTableDataChanged();
    }

    public void initData() throws SQLException {
//        list.add(new User("quangvd", "quang123", "Admin"));
//        list.add(new User("ngocttm", "ngoc123", "User"));
//        list.add(new User("longvh", "long123", "User"));
        Connection con = getConnection();
        Statement stm = con.createStatement();
        ResultSet rs = stm.executeQuery("select * from staff");

        while (rs.next()) {
            list.add(new User(rs.getString("username"), rs.getString("pass_word"), rs.getString("role_user")));
        }
    }

    public void initTable() {
        tblModel = new DefaultTableModel();
        String[] cols = new String[]{"USERNAME", "PASSWORD", "ROLE"};
        tblModel.setColumnIdentifiers(cols);
        tblUser.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        grpRole = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        rdoUser = new javax.swing.JRadioButton();
        rdoAdmin = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("User Management");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Role");

        grpRole.add(rdoUser);
        rdoUser.setText("User");

        grpRole.add(rdoAdmin);
        rdoAdmin.setText("Admin");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoAdmin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtUser)
                    .addComponent(txtPass))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoUser)
                    .addComponent(rdoAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove)
                    .addComponent(btnUpdate)
                    .addComponent(btnReset))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EDITION", jPanel1);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title1", "Title2", "Title3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );

        jTabbedPane1.addTab("LIST", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập username", "Lưu ý", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (User user : list) {
            if (txtUser.getText().equals(user.getUsername())) {
                JOptionPane.showMessageDialog(this, "Username này đã tồn tại", "Lưu ý", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (new String(txtPass.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password", "Lưu ý", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!rdoUser.isSelected() && !rdoAdmin.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò", "Lưu ý", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User user = new User();

        user.setUsername(txtUser.getText());
        user.setPassword(new String(txtPass.getPassword()));
        user.setRole(rdoUser.isSelected() ? "User" : "Admin");

        list.add(user);

        try {
            Connection con = getConnection();
            String sql = "insert into staff values (?, ?, ?);";
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, user.getUsername());
            stm.setString(2, user.getPassword());
            stm.setString(3, user.getRole());
            stm.executeUpdate();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        fillTable();
        JOptionPane.showMessageDialog(this, "Đã thêm");
        btnResetActionPerformed(evt);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập username", "Lưu ý", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (User user : list) {
            if (user.getUsername().equals(txtUser.getText()) && user.getPassword().equals(new String(txtPass.getPassword())) && (rdoUser.isSelected() ? "User" : "Admin") == user.getRole()) {
                int choice = (JOptionPane.showConfirmDialog(this, "Xoá?", "Xác nhận", JOptionPane.YES_NO_OPTION));

                if (choice == JOptionPane.YES_OPTION) {

                    try {
                        Connection con = getConnection();
                        String sql = "delete from staff where username = ? and pass_word = ? and role_user = ?";
                        PreparedStatement stm = con.prepareStatement(sql);
                        stm.setString(1, txtUser.getText());
                        stm.setString(2, new String(txtPass.getPassword()));
                        stm.setString(3, rdoUser.isSelected() ? "User" : "Admin");
                        stm.executeQuery();
                    } catch (SQLException ex) {
                    }

                    list.remove(user);

                    fillTable();
                    JOptionPane.showMessageDialog(this, "Đã xoá");
                    btnResetActionPerformed(evt);
                    return;
                } else {
                    return;
                }
            }
        }

        JOptionPane.showMessageDialog(this, "Không tồn tại username này");
        btnResetActionPerformed(evt);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtUser.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập username", "Lưu ý", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (new String(txtPass.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password", "Lưu ý", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!rdoUser.isSelected() && !rdoAdmin.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò", "Lưu ý", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (User user : list) {
            if (txtUser.getText().equals(user.getUsername())) {
                int choice = (JOptionPane.showConfirmDialog(this, "Bạn muốn cập nhật cho username này?", "Xác nhận", JOptionPane.YES_NO_OPTION));

                if (choice == JOptionPane.YES_OPTION) {
                    user.setPassword(new String(txtPass.getPassword()));
                    user.setRole(rdoUser.isSelected() ? "User" : "Admin");

                    try {
                        Connection con = getConnection();
                        String sql = "update staff set pass_word = ?, role_user = ? where username = ?";
                        PreparedStatement stm = con.prepareStatement(sql);
                        stm.setString(1, new String(txtPass.getPassword()));
                        stm.setString(2, rdoUser.isSelected() ? "User" : "Admin");
                        stm.setString(3, txtUser.getText());
                        stm.executeQuery();
                    } catch (SQLException ex) {
                    }

                    fillTable();
                    JOptionPane.showMessageDialog(this, "Đã cập nhật");
                    btnResetActionPerformed(evt);
                    return;
                } else {
                    btnResetActionPerformed(evt);
                    return;
                }
            }
        }

        JOptionPane.showMessageDialog(this, "Không tồn tại username này");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        int select = tblUser.getSelectedRow();

        if (select >= 0) {
            String username = (String) tblModel.getValueAt(select, 0);
            String password = (String) tblModel.getValueAt(select, 1);
            for (User user : list) {
                if (user.getUsername().equals(username)) {
                    txtUser.setText(username);
                    txtPass.setText(password);
                    if (user.getRole().equals("User")) {
                        rdoUser.setSelected(true);
                    } else {
                        rdoAdmin.setSelected(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_tblUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserForm().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup grpRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoUser;
    private javax.swing.JTable tblUser;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
